### PR TITLE
Stylus Support

### LINKED ISSUE #25: Stylus support?

### PR DESCRIPTION
**Pull request by dukedotdev**
Closes #25. This is marked as beta due to not having addon support, but functioning overall. I'll go back and add addons when I'm back at my desktop in the next few days.

### CODE REVIEW

**Comment by Dyzean** [comment]
I'll mark it as a draft until this pr have full compability with addon. Overall good pr! Thanks!

**Comment by Lassebq** [comment]
Take a look at https://github.com/catppuccin/discord for reference, if you're planning to add customizable variables

**Comment by Lassebq** [comment]
```css
@var select theme "Theme" ["latte:Latte", "frappe:Frappe", "macchiato:Macchiato", "mocha:Mocha*"]
@var select accent "Accent" {"Rosewater": "'rosewater'", "Flamingo": "'flamingo'", "Pink": "'pink'", "Mauve": "'mauve'", "Red": "'red'", "Maroon": "'maroon'", "Peach": "'peach'", "Yellow": "'yellow'", "Green": "'green'", "Teal": "'teal'", "Blue*": "'blue'", "Sapphire": "'sapphire'", "Sky": "'sky'", "Lavender": "'lavender'"}
```

**Comment by Dyzean** [comment]
Thanks for the good PRs! Merged!

**Pull request merged**
