### PR TITLE
Updated classes to be working with Discord Stable 110451 (c233a73)

### PR DESCRIPTION
**Pull request by minhla**
Thanks to laynetheepic on github for making the converting tool.

### CODE REVIEW

**Comment by Dyzean** [comment]
Already pushed a commit with this PR aswell 👍🏼

**Comment by minhla** [comment]
I'd prefer if my PR got merged, but this is okay I guess.

**Comment by Dyzean** [comment]
> I'd prefer if my PR got merged, but this is okay I guess.

haha sorry bout that, i can't merge it cause i want to release v2 too 😅

**Comment by minhla** [comment]
> > I'd prefer if my PR got merged, but this is okay I guess.
> 
> haha sorry bout that, i can't merge it cause i want to release v2 too 😅

It's alright. So is the latest version (v2) available on the [BetterDiscord site](https://betterdiscord.app/theme/Tokyo%20Night)?

**Comment by Dyzean** [comment]
> > > I'd prefer if my PR got merged, but this is okay I guess.
> > 
> > 
> > haha sorry bout that, i can't merge it cause i want to release v2 too 😅
> 
> It's alright. So is the latest version (v2) available on the [BetterDiscord site](https://betterdiscord.app/theme/Tokyo%20Night)?

Its on the site now

**Pull request closed without merging**
