### PR TITLE
Rename classes

### PR DESCRIPTION
**Pull request by maxpixels64**
So they changed the classes 😭 this was a pain to do but i tried to do all of them hopefully
this also fixes forums which was apparently broken according to a friend or smth but whatever

### CODE REVIEW

**Comment by maxpixels64** [comment]
why tf is it four commits i already did those 2 tf

**Comment by maxpixels64** [comment]
friend made aware of emoji issue so i changed that class as well right now

**Comment by maxpixels64** [comment]
if i find one more class i need to change bro

**Comment by maxpixels64** [comment]
the pain of css classes

**Comment by refact0r** [comment]
might want to check out https://syndishanx.github.io/Website/Update_Classes.html

**Comment by maxpixels64** [comment]
> might want to check out https://syndishanx.github.io/Website/Update_Classes.html

Sounds useful, shall check out when I have the chance 👍

**Comment by Dyzean** [comment]
LGTM!

**Pull request merged**
